### ISSUE TITLE
Erro ao reiniciar o container

### ISSUE THREAD

**Issue by vitor-gabriel** [danielAlbuquerque/protheus-docker#1]
Bom dia,

Ao iniciar a base, tudo ocorre bem, ele abre o smartclient cria as tabelas e segue o processo de abertura do ambiente, se eu paro o container ou reinicio, ele começa a me dar o errorlog em anexo:
[error.log](https://github.com/danielAlbuquerque/protheus-docker/files/8959199/error.log)

**Comment by caimcezar** [comment]
O meu apresenta erro ao conectar ao banco de dados.  já apaguei todo o container a corrigi a lib que estava com 9 para 10. iniciei tudo o processo e ainda dá erro de bd.

**Comment by caimcezar** [comment]
Corrigido fazendo alteração do odbc. lib estava com versão 9 e na imagem estava 10 rodando a build novamente corrigiu o problema.

**Comment by danielAlbuquerque** [comment]
> Corrigido fazendo alteração do odbc. lib estava com versão 9 e na imagem estava 10 rodando a build novamente corrigiu o problema.

Boa valeu, vou atualizar o projeto, faz muito tempo que não mexo.

**Comment by danielAlbuquerque** [comment]
> Bom dia,
> 
> Ao iniciar a base, tudo ocorre bem, ele abre o smartclient cria as tabelas e segue o processo de abertura do ambiente, se eu paro o container ou reinicio, ele começa a me dar o errorlog em anexo: [error.log](https://github.com/danielAlbuquerque/protheus-docker/files/8959199/error.log)

![image](https://user-images.githubusercontent.com/6063722/186146386-7145b409-1091-4547-af25-93ffbe8d0c90.png)


eu acho que ta faltando o arquivo de menu, vou fazer um testes com esse projeto hoje e atualizar ele
